name: ModelSim-List
version: 0.04
abstract: Analysis the ModelSim simulator list output
author: Agent Zhang <agent2002@126.com>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
